### ISSUE TITLE
How to resolve differential wheel robot lateral error if the location module is unstable in real world

### ISSUE THREAD

**Issue by orangetcy** [nobleo/tracking_pid#4]
Thanks for your great project.
I am try use this repo to control cleanning robot, and I add a feature can judge whether the robot has reached the target. I found the tracking pid porcess can work well with _**mobile_robot_simulator**_.
But when I move it to a real robot, there are often lateral errors when reaching the target point. It seems caused by unstable location.
Are there any solutions or suggestions for this situation?

**Comment by Timple** [comment]
If you have an unstable localization you will have issues with most local planners. So you probably want to solve that first. If you have unstable localization inputs, you can consider a kalman filter like used in the robot_localization package.
