### ISSUE TITLE
does it perform dynamic obstacle avoidance?

### ISSUE THREAD

**Issue by amyjohansson1994** [nobleo/tracking_pid#6]
Is there a way to get obstacle avoidance working with move_base_flex using tracking_pid as local planner/controller?

**Comment by Timple** [comment]
This package is about accurately following a trajectory for high and predictable performance. To do that it assumes feasible global paths (no obstacles).
So unfortunately that is not a use-case we're going to support. There is a [range](https://github.com/search?l=XML&q=nav_core%3A%3ABaseLocalPlanner&type=Code) of local planners to choose from if you need that feature.
