### ISSUE TITLE
Could not load the plugin with the name "tracking_pid" and the type "tracking_pid/TrackingPidLocalPlanner" 

### ISSUE THREAD

**Issue by amyjohansson1994** [nobleo/tracking_pid#7]
I am facing the below error when I try to use tracking_pid plugin in mbf. 

The tracking_pid controller works fine if I use it as node.

`process[odometry_publisher-1]: started with pid [11379]
process[msg_to_tf-2]: started with pid [11380]
process[pointcloud_to_laserscan-3]: started with pid [11381]
process[map_server_site-4]: started with pid [11386]
process[amcl-5]: started with pid [11388]
process[move_base_flex-6]: started with pid [11394]
process[move_base-7]: started with pid [11399]
[ WARN] [1603760737.217684872]: local_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1603760737.220514480]: local_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1603760737.222742401]: local_costmap: Using plugin "static_layer"
[ INFO] [1603760737.239114038]: Requesting the map...
[ INFO] [1603760737.446612419]: Resizing static layer to 672 X 640 at 0.050000 m/pix
[ INFO] [1603760737.545596220]: Received a 672 X 640 map at 0.050000 m/pix
[ INFO] [1603760737.557226404]: local_costmap: Using plugin "obstacle_layer"
[ INFO] [1603760737.567109004]:     Subscribed to Topics: laser_scan_sensor
[ INFO] [1603760737.599795060]: local_costmap: Using plugin "inflation_layer"
[ WARN] [1603760737.693645234]: global_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1603760737.694742010]: global_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1603760737.696426039]: global_costmap: Using plugin "static_layer"
[ INFO] [1603760737.706885876]: Requesting the map...
[ INFO] [1603760737.710352435]: Resizing costmap to 672 X 640 at 0.050000 m/pix
[ INFO] [1603760737.810073607]: Received a 672 X 640 map at 0.050000 m/pix
[ INFO] [1603760737.820844943]: global_costmap: Using plugin "obstacle_layer"
[ INFO] [1603760737.835055957]:     Subscribed to Topics: laser_scan_sensor
[ INFO] [1603760737.871276862]: global_costmap: Using plugin "inflation_layer"
[ INFO] [1603760738.008209214]: The plugin with the type "full_coverage_path_planner/SpiralSTC" has been loaded successfully under the name "SpiralSTC".

[FATAL] [1603760738.010230248]: Failed to load the tracking_pid/TrackingPidLocalPlanner controller, are you sure it's properly registered and that the containing library is built? According to the loaded plugin descriptions the class tracking_pid/TrackingPidLocalPlanner with base class type mbf_costmap_core::CostmapController does not exist. Declared types are  MultiLibraryClassLoader: Could not create object of class type tracking_pid::TrackingPidLocalPlanner as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[ERROR] [1603760738.010411055]: Could not load the plugin with the name "tracking_pid" and the type "tracking_pid/TrackingPidLocalPlanner"!`

Thank you

**Comment by cesar-lopez-mar** [comment]
Good morning, the current version does not implement a local motion planner plugin. The controller is designed for controlled industrial environments and therefore obstacle avoidance was not required (which is expected from a local planner).  We will remove the unused XML file.
